# Generated by Django 4.2.10 on 2024-03-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('form', models.CharField(choices=[('P', 'Pill'), ('C', 'Capsule'), ('T', 'Tablet'), ('L', 'Liquid'), ('I', 'Injection'), ('D', 'Drops'), ('A', 'Topical'), ('S', 'Suppository'), ('W', 'Powder'), ('Y', 'Spray'), ('Z', 'Lozenge'), ('O', 'Other')], default='P', max_length=1)),
                ('duration', models.CharField(max_length=150)),
                ('notes', models.TextField(max_length=500)),
            ],
        ),
    ]
