# Generated by Django 4.2.10 on 2024-03-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dosage date')),
                ('dosage', models.CharField(max_length=150)),
                ('time', models.TimeField(verbose_name='Dosage time')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.drug')),
            ],
        ),
    ]
