# Generated by Django 4.2.11 on 2024-03-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='drug',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.drug'),
        ),
    ]
